# Code Generated by Sidekick is for learning and experimentation purposes only.
from __future__ import annotations

from fastapi import APIRouter, Depends, status
from sqlalchemy.orm import Session

from app.api.deps import require_admin
from app.core.errors import bad_request, not_found, forbidden
from app.db.models import User, UserRole
from app.db.session import get_db

router = APIRouter(prefix="/admin", tags=["admin"])

def _count_admins(db: Session) -> int:
    return db.query(User).filter(User.role == UserRole.admin).count()

def _to_out(user: User) -> dict:
    return {
        "id": user.id,
        "email": user.email,
        "is_admin": user.role == UserRole.admin,
        "created_at": getattr(user, "created_at", None),
    }

@router.get("/users", status_code=status.HTTP_200_OK)
def list_users(
    db: Session = Depends(get_db),
    me: User = Depends(require_admin),
) -> list[dict]:
    users = db.query(User).order_by(User.created_at.asc()).all()
    return [_to_out(u) for u in users]

@router.post("/users/{user_id}/promote", status_code=status.HTTP_200_OK)
def promote_user(
    user_id: str,
    db: Session = Depends(get_db),
    me: User = Depends(require_admin),
) -> dict:
    user = db.get(User, user_id)
    if not user:
        raise not_found("User not found")
    if user.role != UserRole.admin:
        user.role = UserRole.admin
        db.commit()
        db.refresh(user)
    return _to_out(user)

@router.post("/users/{user_id}/demote", status_code=status.HTTP_200_OK)
def demote_user(
    user_id: str,
    db: Session = Depends(get_db),
    me: User = Depends(require_admin),
) -> dict:
    user = db.get(User, user_id)
    if not user:
        raise not_found("User not found")

    if user.id == me.id:
        # Prevent self-demotion
        raise forbidden("You cannot demote your own admin role")

    if user.role != UserRole.admin:
        # Already not admin
        return _to_out(user)

    if _count_admins(db) <= 1:
        # Prevent removing the last remaining admin
        raise bad_request("Cannot demote the last remaining admin")

    user.role = UserRole.user
    db.commit()
    db.refresh(user)
    return _to_out(user)

@router.delete("/users/{user_id}", status_code=status.HTTP_200_OK)
def delete_user(
    user_id: str,
    db: Session = Depends(get_db),
    me: User = Depends(require_admin),
) -> dict:
    user = db.get(User, user_id)
    if not user:
        raise not_found("User not found")

    if user.id == me.id:
        # Prevent self-delete
        raise forbidden("You cannot delete your own account")

    if user.role == UserRole.admin and _count_admins(db) <= 1:
        # Prevent deleting the last admin
        raise bad_request("Cannot delete the last remaining admin")

    db.delete(user)
    db.commit()
    return {"id": user_id, "deleted": True}
